### ISSUE TITLE
Binsig Function missing

### ISSUE THREAD

**Issue by jatin-hans** [sid8123/Stock-Market-prediction-using-soft-computing#1]
The back propagation program needs binsig function which is missing, only binsig1 is included in the project files.

**Comment by sid8123** [comment]
Please give me 2 days time, as i am busy with some other projects. I will provide u with a detailed documentation by Thursday evening.

**Comment by Zynks** [comment]
Hey Sid, I am waiting for your reply. So if possible provide me your email so we can communicate over it. I am eagerly waiting for your reply. So reply ASAP.

**Comment by sid8123** [comment]
Sorry for late reply, i was involved in another project. You can contact me
through siddharth.shankar.swain@gmail.com or swain.chandan@gmail.com. You
can contact me for any doubt.

**Comment by Zynks** [comment]
Still waiting for your reply.
